name: 'docker-setup'
description: 'Install tools from the container ecosystem'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  only:
    description: 'Space separated list of tools to install'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://nicholasdille/docker-setup:1.4.2'
  args:
  - '--no-wait'
  - '--skip-docs'
  - '--only'
  - ${{ inputs.only }}
