name: 'docker-setup'

description: 'Install tools from the container ecosystem'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  version:
    description: 'Version of docker-setup to use'
    required: false
    default: 'latest'
  tools:
    description: 'List of tools to install (space separated)'
    required: false
  prefix:
    description: 'Directory prefix for tool installation'
    required: false
    default: ''
  skip-conflicts:
    description: 'Skip conflicting tools'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:

  - name: Install docker-setup
    shell: bash
    run: |
      echo "Installing docker-setup"
      echo "Requested version ${{ inputs.version }}"

      url="https://github.com/nicholasdille/docker-setup/releases/latest/download/docker-setup"
      if test "${{ inputs.version }}" != "latest"; then
          url="https://github.com/nicholasdille/docker-setup/releases/download/v${{ inputs.version }}/docker-setup"
      fi

      echo "Using URL ${url}"
      curl --url "${url}" \
          --silent \
          --location \
          --output /usr/local/bin/docker-setup
      chmod +x /usr/local/bin/docker-setup

      docker-setup --version

  - name: Update metadata
    shell: bash
    run: |
      if test -z "${{inputs.tools }}"; then
          echo "No tools requested. Metadata update skipped"
          exit 0
      fi
      echo "Updating metadata"
      docker-setup --prefix=${{ inputs.prefix }} update

  - name: Install tools
    shell: bash
    run: |
      if test -z "${{ inputs.tools }}"; then
          echo "No tools requested"
          exit 0
      fi
      echo "Installing tools"
      docker-setup --prefix=${{ inputs.prefix }} install --skip-conflicts=${{ inputs.skip-conflicts }} ${{ inputs.tools }}