name: 'docker-setup'
description: 'Install tools from the container ecosystem'
inputs:
  only:
    description: 'Tools to install'
    required: false
    default: ''
  tags:
    description: 'Tools with tag to install'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.only }}
  - ${{ inputs.tags }}
