name: 'docker-setup'
description: 'Install tools from the container ecosystem'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  version:
    description: 'Version of docker-setup to use'
    required: false
    default: 'latest'
  check:
    description: 'Check after installation'
    required: false
    default: 'false'
  only:
    description: 'Only install tools specified by <list>'
    required: false
    default: 'false'
  tags:
    description: 'Only install tools with tags specified by <list>'
    required: false
    default: 'false'
  list:
    description: 'Tool names or tags (requires <only> or <tags>)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:

  - name: Install docker-setup
    shell: bash
    run: |
      echo "Requested version ${{ inputs.version }}"

      url="https://github.com/nicholasdille/docker-setup/releases/latest/download/docker-setup.sh"
      if test "${{ inputs.version }}" != "lastest"; then
          url="https://github.com/nicholasdille/docker-setup/releases/download/v${{ inputs.version }}/docker-setup.sh"
      fi

      echo "Using URL ${url}"
      curl "${url}" \
          --silent \
          --location \
          --output /usr/local/bin/docker-setup
      chmod +x /usr/local/bin/docker-setup

      docker-setup --version

  - name: Install tools
    env:
      no_wait: "true"
      only: ${{ inputs.only }}
      tags: ${{ inputs.check }}
    shell: bash
    run: |
      docker-setup ${{ inputs.list }}

  - name: Check installed tools
    if: ${{ inputs.check }}
    env:
      check: "true"
      only: ${{ inputs.only }}
      tags: ${{ inputs.check }}
    shell: bash
    run: |
      docker-setup ${{ inputs.list }}
