name: Tests

on:
  push:
    branches:
      - main

jobs:

  test-full:
    name: Test full installation
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        uses: nicholasdille/docker-setup-action@main

  test-only:
    name: Test only
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        uses: nicholasdille/docker-setup-action@main
        with:
          only: true
          list: "docker yq"

  test-version:
    name: Test version
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        uses: nicholasdille/docker-setup-action@main
        with:
          version: 1.4.3
          only: true
          list: "docker yq"
