name: Tests

on:
  push:
    branches:
    - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

    - name: Install
      uses: nicholasdille/docker-setup-action@main

    - name: Test docker-setup
      run: |
        which docker-setup
        docker-setup --version

    - name: Install
      uses: nicholasdille/docker-setup-action@main
      with:
        prefix: /tmp/docker-setup
        tools: gojq yq

    - name: Check installed tools
      run: |
        docker-setup --prefix=/tmp/docker-setup install --installed --plan

    - name: Test tools
      run: |
        /tmp/docker-setup/usr/local/bin/gojq --version
        /tmp/docker-setup/usr/local/bin/jq --version
        /tmp/docker-setup/usr/local/bin/yq --version