name: Tests

on:
  push:
    branches:
    - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

    - name: Install
      uses: nicholasdille/docker-setup-action@main

    - name: Test
      run: |
        which docker-setup
        docker-setup --version

    - name: Install
      uses: nicholasdille/docker-setup-action@main
      with:
        cache-dir: /tmp/docker-setup/cache
        lib-dir: /tmp/docker-setup/lib
        tools: gojq yq

    - name: Test
      run: |
        docker-setup --prefix="" --cache-directory=/tmp/docker-setup/cache --lib-directory=/tmp/docker-setup/lib install --installed --plan