name: Tests

on:
  push:
    branches:
    - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

    - name: Install
      uses: nicholasdille/docker-setup-action@main

    - name: Test
      run: |
        which docker-setup
        docker-setup --version

    - name: Install
      uses: nicholasdille/docker-setup-action@main
      with:
        prefix: /tmp/docker-setup
        tools: gojq yq

    - name: Test
      run: |
        docker-setup --prefix=/tmp/docker-setup install --installed --plan