name: Tests

on:
  push:
    branches:
      - main

jobs:

  test-full:
    name: Test full installation
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        uses: nicholasdille/docker-setup-action@main
      - name: Store logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-full.zip
          path: /var/log/**

  test-only:
    name: Test only
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        uses: nicholasdille/docker-setup-action@main
        with:
          only: true
          list: "docker yq"
      - name: Store logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-only.zip
          path: /var/log/**

  test-version:
    name: Test version
    runs-on: ubuntu-20.04
    steps:
      - name: Install
        uses: nicholasdille/docker-setup-action@main
        with:
          version: 1.3.14
          only: true
          list: "docker yq"
      - name: Store logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-version.zip
          path: /var/log/**
